execute_process(
    COMMAND iscc "${CMAKE_CURRENT_LIST_DIR}\\main.iss"
    "/O${CPACK_PACKAGE_DIRECTORY}"
    "/F${CPACK_PACKAGE_FILE_NAME}"
    "/DCPACK_PACKAGE_NAME=${CPACK_PACKAGE_NAME}"
    "/DCPACK_PACKAGE_VENDOR=${CPACK_PACKAGE_VENDOR}"
    "/DCPACK_PACKAGE_VERSION=${CPACK_PACKAGE_VERSION}"
    "/DUPGRADE_GUID=${CPACK_WIX_UPGRADE_GUID}"
    RESULT_VARIABLE ISCC_RESULT
)
if(NOT ISCC_RESULT EQUAL "0")
    message(FATAL_ERROR "ISCC failed with exit code ${ISCC_RESULT}")
endif()
